name: Build 1.3.x

on:
  push:
    branches:
      - release-1.3.*
      - v1.3.*
  pull_request:
    branches:
      - release-1.3.*
      - v1.3.*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build Setup
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Build
        run: |
          npm install -g grunt-cli@0.1.13
          npm i
          npm i
          npm run build:app
      - name: Tests
        run: |
          npm run test:app -- --browsers=ChromeHeadless
          npm run e2e
