name: Search for new angular.js CVEs on SNYK

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  build:
    name: Check for new CVEs
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Check CVEs
        run: |
          bash ${GITHUB_WORKSPACE}/scripts/github-actions/check-cves.sh
      - name: Send message to Slack channel
        if: ${{ failure() }}
        uses: bonitasoft/actions/packages/notify-slack@v2.2.0
        with:
          CHANNEL_ID: ${{ secrets.SLACK_RD_CHANNEL_ID }}
          MESSAGE: |
            :x: The CVE count for AngularJs 1.3.20 has changed or could not connect to SNYK

            Check the failing build to see if there are new available CVEs for AngularJs 1.3.20
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
