name: Release angular.js

on:
  workflow_dispatch:
    inputs:
      version:
        description: new version to release ([0-9]+\.[0-9]+\.[0-9]+(-[a-z]+\.[0-9]+)?)
        default: 1.3.18-patched.01
        required: true
      versionName:
        description: new version name (.+)
        default: 1.3.18-patched.01
        required: true

jobs:
  createGithubRelease:
    name: Create release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build Setup
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Build
        run: |
          npm install -g grunt-cli@0.1.13
          npm i
          grunt package
      - name: Tests
        run: |
          grunt test:unit
          grunt test:e2e
      - name: Release
        run: |
          bash ${GITHUB_WORKSPACE}/scripts/github-actions/release.sh --git-push-dryrun=false --version-number=${{ github.event.inputs.version }} --version-name=${{ github.event.inputs.versionName }}

